### ISSUE TITLE
Disconnecting the bot crashes it

### ISSUE THREAD

**Issue by Olebeh** [lolollllo/discord-portable-player#42]
Whenever i disconnect the bot from the voice channel while it's playing, the bot crashes with this error:
```
if (!newState.channelId && oldState.channelId === queue.connection.channel.id) {
                                                                           ^
TypeError: Cannot read properties of null (reading 'id')
```

**Comment by lolollllo** [comment]
Could you show the whole error?

**Comment by Olebeh** [comment]
```if (!newState.channelId && oldState.channelId === queue.connection.channel.id) {
                                                                                                                              ^
TypeError: Cannot read properties of null (reading 'id')
    at Player._handleVoiceState (.\node_modules\discord-portable-player\dist\Player.js:79:88)
    at Client.emit (node:events:539:35)
    at Client.emit (node:domain:475:12)
    at VoiceStateUpdate.handle (.\node_modules\discord.js\src\client\actions\VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (.\node_modules\discord.js\src\client\websocket\handlers\VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (.\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (.\node_modules\discord.js\src\client\websocket\WebSocketShard.js:478:22)
    at WebSocketShard.onMessage (.\node_modules\discord.js\src\client\websocket\WebSocketShard.js:317:10)
    at WebSocket.onMessage (.\neigrabot\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)```

**Comment by lolollllo** [comment]
Can't seem to reproduce this, Though ill look into it and roll out a fix in the next week :)

**Comment by lolollllo** [comment]
Have you tried in the new version?
